### ISSUE TITLE
Npm file should be initialised for design

### ISSUE THREAD

**Issue by OEASLAN** [OEASLAN/cyfres#11]
We want to decide UI frameworks for design.

I love the material design e.g.: http://materializecss.com and I suggest to use it.

Please comment @ugurcanlacin .

**Comment by OEASLAN** [comment]
Also we can use [React](http://facebook.github.io/react/) because it has [Material UI fw](http://material-ui.com). These are new technology for user interfaces. We should create amazing things for ui with using new techs.

**Comment by ugurcanlacin** [comment]
@OEASLAN I analyzed material design and think that It looks pretty cool.We should use it for our project!

Also,Angular Js has Material support at the same time. 
<a href="https://material.angularjs.org/latest/#/">AngularJs with Material Design</a>

React is a good choice if we talk about view rendering which based on performance like a lot of data or list changes dynamically.

**Comment by OEASLAN** [comment]
@ugurcanlacin You can see the performance comparison between react and angular

https://www.codementor.io/reactjs/tutorial/reactjs-vs-angular-js-performance-comparison-knockout

I didn't know react performance but I'm impressed.

However, we may use AngularJS or ReactJS whatever we want.

I vote ReactJS with Material UI. What about you ?

**Comment by ugurcanlacin** [comment]
@OEASLAN okey, comparison is so effective. I agree with you. We should use React with Material UI.

**Comment by OEASLAN** [comment]
I changed the title from bower to npm. I realised that the ui working with nodejs so I will create package.json.

**Comment by OEASLAN** [comment]
@ugurcanlacin I know I have lots of suggestions but , google released polymer project 1.0. It is amazing!

Please check this out and reply me.

**Comment by ugurcanlacin** [comment]
@OEASLAN I looked at that project. It is amazing.However, I prefer more control on our code in terms of js and css.Generally, these kind of things are ready to use it with default  features and that's why I don't suggest JSF. BUT, This project is so different according to others. It gives a possibility to make our components and that shows difference clearly. I would like to work with this.

**Comment by OEASLAN** [comment]
Yes absolutely. I will create bower file as soon as possible.

**Comment by OEASLAN** [comment]
@ugurcanlacin I tested polymer but just new browsers support this fw. I will design the UI with bootstrap if you don't have any problem with this.

**Comment by ugurcanlacin** [comment]
@OEASLAN So, We gave up Material Design right? I am okey in every way.

**Comment by OEASLAN** [comment]
@ugurcanlacin I guess we can handle it with css. I guess I can design it with material design. Thanks
