### ISSUE TITLE
Genre hibernate class cannot insert data into table

### ISSUE THREAD

**Issue by OEASLAN** [OEASLAN/cyfres#12]
Genre hibernate class cannot insert data into table

**Comment by ugurcanlacin** [comment]
We solved this issue last night. Am I right ?

**Comment by OEASLAN** [comment]
No I created genre class but in AppTest it didn't work. User class is working but this is not working.

**Comment by ugurcanlacin** [comment]
Okey,  I solved that issue. You can look at the <a href="https://github.com/OEASLAN/cyfres/commit/26ed5969a10d79ebf7f325818068d805a123feb7">solution </a>

The problem caused by forget to add annotated classes to applicationContext.xml.
